version: "3.8"

services:
  mysql-db:
    image: mysql:8.1
    container_name: marketplace-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build: .
    container_name: marketplace-app
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      - mysql-db

volumes:
  mysql-data: